### ISSUE TITLE
Missing Python Dependencies Not Installed

### ISSUE THREAD

**Issue by heywoodlh** [birlorg/bitwarden-cli#2]
First, thank you so much for an awesome cli! What a great project.

Now to the point: I ran through the install steps for Python on Mac OS X High Sierra and had a whole bunch of dependencies that I had to go in and install manually after running the install. Not sure if anyone else is running into this problem.

Here are the deps I had to install: 
asn1crypto==0.24.0
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
click==6.7
cryptography==2.2.2
docopt==0.6.2
et-xmlfile==1.0.1
idna==2.6
jdcal==1.3
objectpath==0.5
odfpy==1.3.6
openpyxl==2.5.2
psutil==5.4.3
pycparser==2.18
pystandardpaths==0.3.2
PyYAML==3.12
records==0.5.2
requests==2.18.4
rubicon-objc==0.2.10
six==1.11.0
SQLAlchemy==1.2.6
tablib==0.12.1
unicodecsv==0.14.1
urllib3==1.22
xlrd==1.1.0
xlwt==1.3.0

May want to throw that in your setup.py file.

**Comment by birlorg** [comment]
huh. that's not very nice.  It's all in the Pipfile, not sure what's going on.  I'll see why pip is being such a meanie-pants.

**Comment by heywoodlh** [comment]
Lol cool! It took a few minutes to get them all installed and then there wasn't a problem. Not sure if it's specific to my Mac or perhaps my web application firewall installed on it. 

Regardless, let me know if there is any other info you need from me. I would like to know what is causing it as well.

**Comment by birlorg** [comment]
OK. `pip install bitwarden==0.2.2`  (or just a `pip install bitwarden` ) now should fix this.  It does for me anyway :)

since you are on a mac, check out slab mode, I recommend: `brew install choose-gui`. and then `bitwarden slab` will be all the more amazing. more info on the chooser here: https://github.com/sdegutis/choose

Let me know what you think! :)
