### ISSUE TITLE
File Does Not Exist

### ISSUE THREAD

**Issue by heywoodlh** [birlorg/bitwarden-cli#3]
When I run the initial login command this is what I get:

`OSError: DB sqlite:////Users/username/Library/Application Support/birl.org/bitwarden/bitwarden.sqlite does not exist: You need to run tools/lb.sh`

I installed bitwarden-cli via Pip so I had to clone the repository in order to run `tools/lb.sh`. When I try running`tools/lb.sh` this is the error that I get:

`./tools/lb.sh: line 12: --classpath=/Users/username/git/bitwarden-cli/tools/sqlite-jdbc-3.21.0.1.jar: No such file or directory`

How do I fix this? 

Also, since this program is in Pypi is there any way that the Pip installation can run `tools/lb.sh` somehow? I understand that it is referencing a jar file but it seems a little backwards to install the program via `pip` only to have to download the repository and run `tools/lb.sh` anyway.

Just a thought. I understand that the program isn't in production yet, so I understand that it isn't a finished product.

**Comment by birlorg** [comment]
Yes, Liquibase(LB) is a java mess, so you have to do a lot to make it behave.  But I really didn't want to deal with DB schema's in my code, and LB is very good at it.

curl -o bitwarden.sqlite https://github.com/birlorg/bitwarden-cli/raw/trunk/tools/bitwarden.sqlite

then move the bitwarde.sqlite file to the correct path (which is different on every platform).

Eventually I plan on it just doing a requests.get() and download the file for you.

alternatively just copy the bitwarden.sqlite file to the path

i.e. cp bitwarden.sqlite /Users/username/Library/Application Support/birl.org/bitwarden/bitwarden.sqlite

you may have to mkdir -p /Users/username/Library/Application Support/birl.org/bitwarden/bitwarden.sqlite

first
and obviously change s/username/heywoodlh/ first for the above paths.

**Comment by birlorg** [comment]
have it give you the mkdir and curl commands instead of messing with liquibase, as it's not a end-user friendly tool.

**Comment by heywoodlh** [comment]
Awesome, that fixed that issue. I have another issue not related to this so I will open that up.
