### ISSUE TITLE
Doesn't compile on FreeBSD and Linux

### ISSUE THREAD

**Issue by alldigital** [birlorg/bitwarden-cli#5]
Can't compile rust version neither on FreeBSD 11.1 nor on Arch Linux.
The compile error is like follows (on both FreeBSD and Arch):
   Compiling bitwarden v0.1.0 (file:///home/ed/code/alien/bitwarden-cli/rust)
error[E0433]: failed to resolve. Use of undeclared type or module `rand`
  --> src/crypto.rs:96:19
   |
96 |     let mut rng = rand::thread_rng();
   |                   ^^^^ Use of undeclared type or module `rand`

Let me know if any additional info needed.

**Comment by birlorg** [comment]
The rust version is not functional yet.  Patches welcome!  The agent in rust compiled and worked for me once, against the python version.  It is lacking in error handling however, so can crash very easily.

The python version is implemented and should work well, the big missing piece is it doesn't do the crypto for organizational password sharing, I just haven't gotten that far yet.

**Comment by birlorg** [comment]
Also, the latest rust sources are only in the fossil repo (and they should compile), I only mirror into github @ release time, usually.
